#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logo_footer = "images/logo-footer.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_footer_width = "180px"
logo_width = "110px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = false
# logo text will only show when logo is missing.
logo_text = "Biztrox"
# purgeCSS
purge_css = true
# Main Sections
mainSections = ["blog"]
# image gallery shortcode
image_gallery = true
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_adsense = "" # example: ca-pub-xxxxxxxxxxxxxxxx
google_tag_manager = "" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
copyright = "Copyright by your company"
theme_copyright = true

# footer content
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim." 


# Preloader
[preloader]
enable = true 
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "get a quote"
link = "contact"

# contact info
[contact_info]
address = "9567 Turner Trace Apt. BC C3G8A4"
email = "info@companyname.com"
mobile = "+211234565523"

# Subscription
[subscription] 
enable = true
# subscribe
title = "Subscribe Us"
content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# Crisp Chat
[crisp_chat]
enable = false 
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
author = "Themefisher" 
description = "This is meta description" 
image = "images/favicon.png" # this image will be used as fallback if a page has no image of its own
bg_image = "images/background/page-title.jpg" # this image will be used as fallback if a page has no image of its own
keywords = ["Boilerplate", "Hugo", "Themefisher", "GetHugoThemes"] 

# matomo tracking: see https://matomo.org/
[matomo]
enable = false 
id = "" # your matomo id
url = "" # your matomo url

# baidu analytics: see https://tongji.baidu.com/
[baidu]
analytics_id = "" # Your ID
enable = false 

# plausible analytics: see https://plausible.io/
[plausible]
domain = "" # yourdomain.com
enable = false 

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false 
username = "" # your username

# site verifications
[site_verification]
baidu = "" # Your verification code
bing = "" # Your verification code
facebook = "" # Your verification code
google = "" # Your verification code
mastodon = "" # Your verification code

# google map
[google_map]
enable = true 
address = "https://www.google.com/maps/embed/v1/place?q=Hollywood+coffee+club,+Riyadh+Saudi+Arabia&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"

# cookies
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2

############################# social site ########################
[[social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#" 
title = "facebook" 

[[social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#" 
title = "twitter"  

[[social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "#" 
title = "instagram" 

[[social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#" 
title = "github" 

[[social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#" 
title = "linkedin"
